apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  name: sample
spec:
  dspVersion: v2
  apiServer:
    deploy: true
    enableOauth: false
    enableSamplePipeline: true
   # caBundleFileMountPath: /dspa/custom-certs
   # caBundleFileName: custom.crt
    cABundle:
      configMapName: nginx-tls-config
      configMapKey: rootCA.crt
    resources:
      limits:
        cpu: 20m
        memory: 500Mi
      requests:
        cpu: 20m
        memory: 100m  
  objectStorage:
    minio:
      deploy: true
      image: 'quay.io/opendatahub/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance'
  mlpipelineUI:
    image: quay.io/opendatahub/ds-pipelines-frontend:latest
