apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  name: sample
spec:
  dspVersion: v2
  apiServer:
    deploy: true   
    enableSamplePipeline: true 
    # If developing against a cluster using self-signed certs, then uncomment this field.
    cABundle:
      configMapName: kube-root-ca.crt
      configMapKey: ca.crt
      caBundleMountPath: /etc/ssl/certs
  objectStorage:
    minio:
      deploy: true
      image: 'quay.io/opendatahub/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance'
  mlpipelineUI:
    image: quay.io/opendatahub/ds-pipelines-frontend:latest
