apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: self-signed-ca
    files:
      - rootCA.crt
secretGenerator:
  - name: self-signed-certs
    files:
      - domain.crt
      - domain.key