apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pypiserver.yaml
  - pvc.yaml
  - service.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: tls-config
    files:
      - z-custom-my.cnf
patches:
  - path: pypiserver.yaml