apiVersion: apps/v1
kind: Deployment
metadata:
  name: pypi-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pypi-server
  template:
    metadata:
      labels:
        name: pypi-server
    spec:
      containers:
        - image: "quay.io/harshad16/pypi-server"
          imagePullPolicy: IfNotPresent
          name: pypi-server
          command: 
            - pypi-server
          args:
            - run
            - '--host'
            - '0.0.0.0'
            - '--port'
            - '8080'
            - '--disable-fallback'
            - '--verbose'
            - '/opt/app-root/packages'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "500m"
              memory: 1Gi
            limits:
              cpu: "500m"
              memory: 1Gi
          volumeMounts:
            - mountPath: /opt/app-root/packages
              name: pypi-datastore
            - mountPath: /.pypi-server/certs
              name: pypi-server-certs
            - mountPath: /etc/my.cnf.d/z-custom-my.cnf
              name: tls-config
              subPath: z-custom-my.cnf
            - name: ca-bundle
              mountPath: /.pypi-server/certs/CAs
      volumes:
        - name: pypi-datastore
          persistentVolumeClaim:
            claimName: pypi-datastore
        - name: pypi-server-certs
          secret:
            defaultMode: 420
            items:
              - key: domain.crt
                path: public.crt
              - key: domain.key
                path: private.key
            secretName: self-signed-certs
        - name: tls-config
          configMap:
            name: tls-config
        - name: ca-bundle
          configMap:
            name: self-signed-ca
            items:
              - key: rootCA.crt
                path: public.crt
