apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
patchesStrategicMerge:
  - deployment.yaml
  - route.yaml
  - route-console.yaml
  - service.yaml
  - pvc.yaml
  - secret.yaml