kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: minio-secure
spec:
  to:
    kind: Service
    name: minio
    weight: 100
  port:
    targetPort: https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect