name: KinD DSPO/DSP Integration Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - go.mod
      - go.sum
      - controllers/**
      - api/**
      - config/**
      - tests/**
    types:
      - opened
      - reopened
      - closed
      - synchronize

concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  IMAGE_REPO_DSPO: data-science-pipelines-operator
  DSPA_NAMESPACE: test-dspa
  DSPA_NAMESPACE_EXTERNAL: test-dspa-external
  MINIO_NAMESPACE: test-minio
  DSPA_NAME: test-dspa
  DSPA_NAME_EXTERNAL: test-dspa-external
  DSPA_DEPLOY_WAIT_TIMEOUT: 300
  INTEGRATION_TESTS_DIR: ${{ github.workspace }}/tests
jobs:
  dspo-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.19.x'
        id: go

      - name: Setup and start KinD cluster
        uses: ./.github/actions/kind

      # TODO: Consolidate testing CRDS (2 locations)
      - name: Apply OCP CRDs
        env:
          RESOURCES_DIR: ${{ github.workspace }}/.github/resources
          CONFIG_DIR: ${{ github.workspace }}/config
        run: |
          kubectl apply -f ${{ env.RESOURCES_DIR }}/crds
          kubectl apply -f ${{ env.CONFIG_DIR }}/crd/external/route.openshift.io_routes.yaml

      - name: Build image
        env:
          DSPO_IMAGE: ${{env.REGISTRY_ADDRESS}}/data-science-pipelines-operator
        run: |
          make podman-build -e IMG="${DSPO_IMAGE}"

      - name: Create opendatahub namespace
        run: |
          kubectl create namespace opendatahub

      - name: Deploy Argo Lite
        working-directory: ${{ github.workspace }}/.github/resources/argo-lite
        run: |
          kustomize build . | kubectl apply -f -

      - name: Deploy DSPO
        env:
          DSPO_IMAGE: ${{env.REGISTRY_ADDRESS}}/data-science-pipelines-operator
        run: |
          make podman-push -e IMG="${DSPO_IMAGE}"
          make deploy-kind -e IMG="${DSPO_IMAGE}"
      
      - name: Create Minio Namespace
        run: |
          kubectl create namespace ${{ env.MINIO_NAMESPACE }}
      
      - name: Deploy Minio
        working-directory: ${{ github.workspace }}/.github/resources/minio
        run: |
          kustomize build . |  oc -n ${{ env.MINIO_NAMESPACE }} apply -f -

      - name: Wait for DSPO and Argo deployment
        run: |
          kubectl wait -n opendatahub --timeout=60s --for=condition=Available=true deployment data-science-pipelines-operator-controller-manager
          kubectl wait -n opendatahub --timeout=60s --for=condition=Available=true deployment argo-server          

      - name: Get Minio Route
        id: get_minio_route
        run: |
          minio_route=$(oc get routes -n ${{ env.MINIO_NAMESPACE }} -o=jsonpath='{.items[?(@.metadata.name=="minio-secure")].spec.host}')
          echo "::set-output name=minio_route::$minio_route"
      
      - name: Update DSPA-Lite YAML
        run: |
          sed -i "s|{{MINIO_ROUTE_PLACEHOLDER}}|${{ steps.get_minio_route.outputs.minio_route }}|g" tests/resources/dspa-lite.yaml

      - name: Create DSPA Namespace
        run: |
          kubectl create namespace ${{ env.DSPA_NAMESPACE }}

      - name: Create DSPA Namespace with External Connections
        run: |
          kubectl create namespace ${{ env.DSPA_NAMESPACE_EXTERNAL }}
      
      - name: Create Minio Secrets
        run: |
          kubectl create secret generic minio --from-literal=accesskey=accesskey --from-literal=secretkey=secretkey -n ${{ env.DSPA_NAMESPACE_EXTERNAL }}
      
      - name: Run tests
        working-directory: ${{ github.workspace }}
        env:
          NAMESPACE: ${{ env.DSPA_NAMESPACE }}
          DSPA_NAME: ${{ env.DSPA_NAME }}
        run: |
          make integrationtest K8SAPISERVERHOST=$(oc whoami --show-server) DSPANAMESPACE=${NAMESPACE}

      - name: Run tests for DSPA with External Connections
        working-directory: ${{ github.workspace }}
        env:
          NAMESPACE: ${{ env.DSPA_NAMESPACE_EXTERNAL }}
          DSPA_NAME: ${{ env.DSPA_NAME_EXTERNAL }}
        run: |
          make integrationtest K8SAPISERVERHOST=$(oc whoami --show-server) DSPANAMESPACE=${NAMESPACE}

      - name: Clean up
        run: |
          make undeploy-kind
